###
GET {{protocol}}{{host}}:{{port}}/hse24/categories
content-type: application/json

###
GET http://data.fixer.io/api/convert?access_key=bbac5b49d9915c7e9c7d64ed15618d79&from=GBP&to=JPY&amount=25
content-type: application/json

###
GET http://data.fixer.io/api/latest?access_key=bbac5b49d9915c7e9c7d64ed15618d79