GET {{protocol}}{{host}}:{{port}}/exchange-rate-service/currencies/reference-rate?source=USD&target=EUR
content-type: application/json

###
GET {{protocol}}{{host}}:{{port}}/exchange-rate-service/currencies/convert-rate?source=EUR&target=GBP&sourceAmount=1
content-type: application/json

###
GET {{protocol}}{{host}}:{{port}}/exchange-rate-service/currencies
content-type: application/json


