GET {{protocol}}{{host}}:{{port}}/currencies/reference-rate?source=USD&target=GBP
content-type: application/json

###
GET {{protocol}}{{host}}:{{port}}/currencies/convert-rate?source=EUR&target=GBP&sourceAmount=1
content-type: application/json

###
GET {{protocol}}{{host}}:{{port}}/currencies
content-type: application/json


